[package]
name = "yap-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
tui-tree-widget = "0.23.0"
uuid = { version = "1.16.0", features = ["v4"] }
yap-core = { path = "../yap-core" }
tree-ds = "0.1.6"
